/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example


fun main() {
    println ("¡Hola, Kotlin!")
    
    val nombre = "Iker"
    val apellido = "salinas"
    val fecha = "22/04"
    
    println("mi nombre es $nombre $apellido")
    println("Hoy es $fecha")
}
